### ISSUE TITLE
[FEATURE] group_id로 지글 공지 조회하는 api 추가

### ISSUE THREAD

**Issue by controlZ** [gsainfoteam/ziggle-be#114]
### Description

그룹 상세페이지에서 업로드한 공지를 보여주기 위함

### Todos
- [x] group_tb에 group_id 컬럼 추가
- [x] notice_tb에 있는 group 관련 fk 변경(name -> id)
- [ ] group_id로 지글 공지 조회하는 api 추가
