### ISSUE TITLE
[FEATURE] deadline-detection 기능 crawl에 붙이기

### ISSUE THREAD

**Issue by inthree3** [gsainfoteam/ziggle-be#54]
### Description

현 ziggle-be의 crawl에는 deadline이 정의되어 있지 않아. deadline-detection 기능을 사용할 수 없습니다. 기능이 붙도록 코드 수정이 필요합니다.

### Todos

- [x] ERD/database.dbml 수정
- [x] prisma/schema.prisma 수정
- [x] src/crawl 수정
- [x] CreateCrawlDto 수정
- [x] refectoring

**Comment by inthree3** [comment]
아 shit.... Gitlens로 branch 관리했더니 master랑 local branch랑 동시에 checkout된? 기묘한 상태로 master branch로 신나게 작업하고 있었네요.... 죄송합니다 😭😭
![image](https://github.com/gsainfoteam/ziggle-be/assets/42310616/fd08ee96-18a0-40c7-956f-30cdcc4ced1b)
잘 돌아가용
